apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-deployment
  namespace: chandana-ns
  labels:
    app: fitness
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: fitness1
  template:
    metadata:
      labels: 
        app: fitness1 
    spec: 
      containers: 
        - name: fitness-containers
          image: muralisocial123/transaction-app:v1.0.0
          ports: 
            - containerPort: 3000
--- # creating new yaml file
apiVersion: v1
kind: Service
metadata:
  name: fitness-deployment-svc
  namespace: chandana-ns
spec: 
  selector:  
    app: fitness1 
  ports:
    - port: 3001 #it is a service port number(host)---where we are using this to expose application to internet
      targetPort: 3000 #container port number
      protocol: TCP
  type: ClusterIP
  
