apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-deployment
  namespace: chandana-ns
  labels:
    app: fitness
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: fitness1
  template:
    metadata:
      labels: 
        app: fitness1 
    spec: 
      containers: 
        - name: fitness-containers
          image: muralisocial123/kyndrl-flower-app:v1.1.0
          ports: 
            - containerPort: 3015