apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: flower-app
  namespace: chandana-ns
  labels:
    app-new: flower-app-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app-new: flower
  template:
    metadata:
      labels:
        app-new: flower 
    spec:
      containers:
        - name: flower-container-new
          image: muralisocial123/flipkart-app-web:v1.1.0
          ports:
            - containerPort: 3015

